### ISSUE TITLE
Animated GIFs on lab requirements

### ISSUE THREAD

**Issue by dande313** [learn-co-curriculum/react-event-system-lab#8]
More of a comment, but those animated GIFs, constantly, quickly moving, without the ability to scroll past them, was very distracting while working on this lab. Fortunately, we know how to disable them in the console, but it would be nice to keep them at the top (so we can scroll on by), or not have them.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @dande313 .

We have updated the materials and removed the second animated GIFs to minimize distraction.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
